[package]
name = "no3gameface/bootlebreak"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Promise = "evaera/promise@^4"
Component = "sleitnick/component@^2"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Trove = "sleitnick/trove@^1"
Roact = "roblox/roact@^1.4.0"
Rodux = "roblox/rodux@^3.0.0"
